name: Commit Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  commitizen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-commitizen
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen
      - name: commitizen check
        run: cz check --rev-range origin/main..HEAD
